### ISSUE TITLE
Model downloding issue when computing SER_FIQ

### ISSUE THREAD

**Issue by zycheiheihei** [ziyannchen/VFRxBenchmark#3]
I got an ImportError when I try to compute the metric of SER-FIQ.

Traceback (most recent call last):
  File "scripts/inference_with_metrics.py", line 102, in <module>
    main(root_path)
  File "scripts/inference_with_metrics.py", line 86, in main
    metric_results[target_metric].append(calculate_metric(dict(data=eval_data), metric_opt))
  File "/opt/local-path-provisioner/zhangyichi/video-face-restoration/VFRxBenchmark/bfrxlib/metrics/__init__.py", line 28, in calculate_metric
    metric = METRIC_REGISTRY.get(metric_type)(**data, **opt)
  File "/opt/local-path-provisioner/zhangyichi/video-face-restoration/VFRxBenchmark/bfrxlib/metrics/serfiq_metric.py", line 25, in calculate_serfiq
    model = SER_FIQ(gpu=0 if device == 'cuda' else None)
  File "/opt/local-path-provisioner/zhangyichi/video-face-restoration/VFRxBenchmark/bfrxlib/metrics/serfiq/face_image_quality.py", line 63, in __init__
    from bfrxlib.utils.misc import uncompress_file
ImportError: cannot import name 'uncompress_file' from 'bfrxlib.utils.misc' (/VFRxBenchmark/bfrxlib/utils/misc.py)

**Comment by ziyannchen** [comment]
Hello, there's a problem in this downloading script currently.
I recommend to download the model file mannually [here](https://drive.google.com/file/d/17fEWczMzTUDzRTv9qN3hFwVbkqRD7HE7/view), then uncompress it within `bfrxlib/metrics/serfiq/insightface/model/`.

**Comment by zycheiheihei** [comment]
Thank you!
However, serfiq/insightface/mtcnn-model/det1-0001.params for MTCNN is also missing. Can you provide another download link?

**Comment by ziyannchen** [comment]
[SER-FIQ](https://github.com/pterhoer/FaceImageQuality) includes the weights in their repo, see this [source](https://github.com/pterhoer/FaceImageQuality/tree/master/insightface/mtcnn-model). Download directly of all the `.params` and `.caffemodel` files (with a prefix from `det1` to `det4`) in the `serfiq/insightface/mtcnn-model/`.
